sonar.projectKey=monorepo-ci-cd
sonar.projectName=Monorepo CI CD
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=src/backend/coverage/lcov.info,src/frontend/coverage/lcov.info